version: "3.8"

networks:
  cooking-blog:
    name: "cooking-blog-network"

services:
  nginx:
    container_name: cookingblog
    image: nginx:1.19-alpine
    restart: always
    networks:
      - cooking-blog
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
