version: "3.8"

networks:
  cooking-blog:
    name: "cooking-blog-network"
  default:
    external: true
    name: "default-network"

services:
  cookingblog:
    container_name: cookingblog
    image: nginx:1.19-alpine
    restart: always
    networks:
      - cooking-blog
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./client/build:/usr/share/nginx/html

  cookingblogexporter:
    container_name: cookingblogexporter
    build: ./nginxexporter
    command: "-nginx.scrape-uri http://cooking-blog:9113/stub_status"
    restart: unless-stopped
    depends_on:
      - cookingblog
    networks:
      - default
    labels:
      org.label-schema.group: "monitoring"
