FROM node:14-alpine

WORKDIR /app

COPY ./dist/apps/api  .
COPY ./apps/api/.env .env

RUN mkdir /.logs
RUN ls -al

RUN apk --no-cache add --virtual builds-deps build-base python
RUN yarn install --prod
RUN yarn add tslib compression dotenv redis axios

CMD node ./main.js