module.exports = {
  projects: [
    '<rootDir>/apps/blog',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api/routes',
    '<rootDir>/libs/api/controllers',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/shared/data-access/cooking-blog-api',
    '<rootDir>/libs/blog/data-access',
    '<rootDir>/libs/shared/web/utils',
    '<rootDir>/libs/blog/ui/components',
    '<rootDir>/libs/blog/ui/views',
    '<rootDir>/libs/blog/utils',
    '<rootDir>/libs/shared/utils',
    '<rootDir>/libs/shared/web/hooks',
    '<rootDir>/libs/blog/ui/templates',
    '<rootDir>/libs/shared/api/utils',
    '<rootDir>/libs/shared//exception',
  ],
};
